# Naruto Public API

In [3]:
import requests
import pandas as pd

In [2]:
URL = "https://dattebayo-api.onrender.com/characters"

req = requests.get(URL)

In [4]:
req

In [ ]:
json_data = req.json() # Converting into json format
json_data

{'characters': [{'id': 1344,
   'name': 'Naruto Uzumaki',
   'images': ['https://static.wikia.nocookie.net/naruto/images/d/d6/Naruto_Part_I.png',
    'https://static.wikia.nocookie.net/naruto/images/7/7d/Naruto_Part_II.png'],
   'debut': {'manga': 'Naruto Chapter #1',
    'anime': 'Naruto Episode #1',
    'novel': 'Naruto: Innocent Heart, Demonic Blood',
    'movie': 'Naruto the Movie: Ninja Clash in the Land of Snow',
    'game': 'Naruto: Konoha Ninpōchō',
    'ova': 'Find the Four-Leaf Red Clover!',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Minato Namikaze',
    'mother': 'Kushina Uzumaki',
    'son': 'Boruto Uzumaki',
    'daughter': 'Himawari Uzumaki',
    'wife': 'Hinata Uzumaki',
    'adoptive son': 'Kawaki',
    'godfather': 'Jiraiya'},
   'jutsu': ['All Directions Shuriken',
    'Baryon Mode',
    'Big Ball Rasengan',
    'Big Ball Rasenshuriken',
    'Big Ball Spiralling Serial Zone Spheres',
    'Boil Release: Unrivalled Strength',
    'Chakra Transfer Technique',
    'Clone Body Blow',
    'Clone Flying Arrow',
    'Clone Spinning Heel Drop (Anime only)',
    'Combination Transformation',
    'Continuous Tailed Beast Balls',
    'Crescent Moon Rasengan',
    'Earth Release: Earth-Style Wall',
    'Erupting Propulsion Fist',
    'Fire Release: Toad Oil Flame Bullet (Anime only)',
    'Frog Kata',
    'Frog Strike',
    'Gelel Rasengan',
    'Gentle Step Spiralling Twin Lion Fists',
    'Guts Rasengan',
    'Harem Technique',
    'Hurricane Thunderclap — Majestic Attire Sword Stroke',
    'Ink Creation',
    'Kurama Arm Attack',
    'Mini-Rasenshuriken',
    'Multiple Shadow Clone Technique',
    'Naruto Region Combo',
    'Naruto Uzumaki Combo',
    'Naruto Uzumaki Two Thousand Combo',
    "Naruto and Shion's Super Chakra Rasengan",
    'Negative Emotions Sensing',
    'New Sexy Technique',
    'Nine-Tails Chakra Mode',
    'Ninja Art: Bare-Handed Blade Block',
    'One Thousand Years of Death',
    'Pachinko Technique (Anime only)',
    'Parachute',
    'Parent and Child Rasengan',
    'Planetary Rasengan',
    'Rasengan',
    'Rasengan: Flash',
    'Regeneration Ability',
    'Runt Ball Rasengan (Anime only)',
    'Sage Art: Lava Release Rasenshuriken',
    'Sage Art: Magnet Release Rasengan',
    'Sage Art: Many Ultra-Big Ball Spiralling Serial Spheres',
    'Sage Art: Super Tailed Beast Rasenshuriken',
    'Sage Mode',
    'Scorch Release: Halo Hurricane Jet Black Arrow Style Zero',
    'Seven-Coloured Rasengan',
    'Sexy Reverse Harem Technique',
    'Sexy Technique',
    'Sexy Technique: Pole Dance and Nice Body (Anime only)',
    'Shadow Clone Technique',
    'Shadow Shuriken Technique',
    'Shuriken Shadow Clone Technique (Anime only)',
    'Six Paths Sage Mode',
    'Six Paths Senjutsu',
    'Six Paths Yang Power',
    'Six Paths — Chibaku Tensei',
    'Six Paths: Ultra-Big Ball Rasenshuriken',
    'Soap Bubble Ninjutsu (Anime only)',
    'Spiralling Absorption Sphere',
    'Spiralling Serial Spheres',
    'Spiralling Strife Spheres',
    'Strong Fist (Anime only)',
    'Summoning Technique (Toad)',
    'Summoning: Food Cart Destroyer Technique',
    'Super Mini-Tailed Beast Ball',
    'Super-Ultra-Big Ball Rasengan',
    'Supreme Ultimate Rasengan',
    'Tailed Beast Ball',
    'Tailed Beast Ball Rasenshuriken',
    'Tailed Beast Chakra Arms',
    'Tailed Beast Full Charge',
    'Tailed Beast Rasengan',
    'Tailed Beast Shockwave',
    'Torii Seal',
    'Tornado Rasengan',
    'Truth-Seeking Ball',
    'Turning into a Frog Technique (Anime only)',
    'Typhoon Water Vortex Technique',
    'Ultra-Big Ball Rasengan',
    'Ultra-Many Spiralling Serial Spheres',
    'Uzumaki Formation (Anime only)',
    'Wind Release: Rasengan',
    'Wind Release: Rasenshuriken',
    'Wind Release: Repeated Rasenshuriken',
    'Wind Release: Toad Gun (Anime only)',
    'Wind Release: Toad Oil Bullet (Anime only)',
    'Wind Release: Toad Oil Flame Bullet (Anime only)',
    'Wind Release: Ultra-Big Ball Rasenshuriken',
    'Wisdom Wolf Decay'],
   'natureType': ['Wind Release  (Affinity)',
    'Lightning Release',
    'Earth Release',
    'Water Release',
    'Fire Release',
    'Lava Release',
    'Magnet Release',
    'Boil Release',
    'Yin Release',
    'Yang Release',
    'Yin–Yang Release'],
   'personal': {'birthdate': 'October 10',
    'sex': 'Male',
    'age': {'Part I': '12–13', 'Part II': '15–17', 'Academy Graduate': '12'},
    'height': {'Part I': '145.3cm - 147.5cm',
     'Part II': '166cm',
     'Blank Period': '180cm'},
    'weight': {'Part I': '40.1kg - 40.6kg', 'Part II': '50.9kg'},
    'bloodType': 'B',
    'kekkeiGenkai': ['Lava Release', 'Magnet Release', 'Boil Release'],
    'classification': ['Jinchūriki', 'Sage', 'Sensor Type'],
    'tailedBeast': 'Shukaku, Matatabi, Isobu, Son Gokū, Kokuō, Saiken, Chōmei, Gyūki, Kurama (Forms)',
    'occupation': ['Hokage', 'Chūnin Exams Proctor  (Anime only)'],
    'affiliation': ['Konohagakure', 'Mount Myōboku', 'Allied Shinobi Forces'],
    'team': ['Team Kakashi',
     'Sasuke Recovery Team',
     'Konoha 11  (Anime only)',
     'Bikōchū Search Team  (Anime only)',
     'Kaima Capture Team  (Anime only)',
     'Star Guard Team  (Anime only)',
     'Peddlers Escort Team  (Anime only)',
     'Kazekage Rescue Team',
     'Team One  (Anime only)',
     'Eight Man Squad',
     'Hanabi Rescue Team  (Movie only)'],
    'clan': 'Uzumaki',
    'titles': ['うずまきナルトUzumakiNaruto',
     'the-off,NumberOneUnpredictable,NoisyNinja(目立ちたがり屋で意外性no.1のドタバタ忍者,MedachitagariyaDeIgaiseiNanbāWanNoDotabataNinja,EnglishTv:NumberOneHyperactive,KnuckleheadNinja)',
     'childOfTheProphecy(予言の子,YogenNoKo)',
     'saviourOfThisWorld(この世の救世主,KonoYoNoKyūseishu)',
     'heroOfTheHiddenLeaf(木ノ葉隠れの英雄,KonohagakureNoEiyū,LiterallyMeaning:HeroOfTheHiddenTreeLeaves)',
     'boyOfMiracles(奇跡を起こす少年,KisekiOOkosuShōnen)',
     "konoha'sOrangeHokage(木ノ葉のオレンジ火影,KonohaNoOrenjiHokage,LiterallyMeaning:TreeLeaves'OrangeFireShadow)",
     'seventhHokage(七代目火影,NanadaimeHokage,LiterallyMeaning:SeventhFireShadow)',
     'fox(狐,Kitsune)']},
   'rank': {'ninjaRank': {'Part I': 'Genin', 'Gaiden': 'Kage'},
    'ninjaRegistration': '012607'},
   'tools': ['Absorbing Hand',
    'Bō (Anime only)',
    'Chakra Blade (Anime only)',
    'Flying Thunder God Kunai',
    'Fūma Shuriken',
    'Hidden Kunai Mechanism',
    'Konoha Chakra Blade',
    'Sand',
    'Stone of Gelel'],
   'voiceActors': {'japanese': ['Junko Takeuchi',
     'Ema Kogure   (Sexy Technique)'],
    'english': ['Maile Flanagan',
     'Stephanie Sheh   (Sexy Technique)',
     'Jeannie Elias   (Sexy Technique) (episode 53-55)',
     'Mary Elizabeth McGlynn   (Sexy Technique) (episode 177)',
     'Kate Higgins   (Sexy Technique) (episode 229)']}},
  {'id': 1307,
   'name': 'Sasuke Uchiha',
   'images': ['https://static.wikia.nocookie.net/naruto/images/2/21/Sasuke_Part_1.png',
    'https://static.wikia.nocookie.net/naruto/images/1/13/Sasuke_Part_2.png'],
   'debut': {'manga': 'Naruto Chapter #3',
    'anime': 'Naruto Episode #1',
    'novel': 'Naruto: Innocent Heart, Demonic Blood',
    'movie': 'Naruto the Movie: Ninja Clash in the Land of Snow',
    'game': 'Naruto: Konoha Ninpōchō',
    'ova': 'Find the Four-Leaf Red Clover!',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Fugaku Uchiha',
    'mother': 'Mikoto Uchiha',
    'brother': 'Itachi Uchiha',
    'daughter': 'Sarada Uchiha',
    'wife': 'Sakura Uchiha'},
   'jutsu': ['Afterglow',
    'Amaterasu',
    'Amaterasu: Flame Wrapping Fire',
    'Amenotejikara',
    'Animal Path',
    'Area Scanning Technique',
    'Asura Path',
    "Banshō Ten'in (Anime only)",
    'Binding Snake Glare Spell',
    'Blaze Release: Honoikazuchi (Anime only)',
    'Blaze Release: Kagutsuchi',
    'Blaze Release: Susanoo Kagutsuchi',
    'Blaze Release: Yasaka Magatama',
    'Chibaku Tensei',
    'Chidori',
    'Chidori Current',
    'Chidori Light Sword',
    'Chidori Senbon',
    'Chidori Sharp Spear',
    'Coercion Sharingan',
    'Combination Transformation (Anime only)',
    'Cursed Seal of Heaven',
    'Demonic Illusion: Mirage Crow',
    'Demonic Illusion: Shackling Stakes Technique',
    'Deva Path',
    'Earth Release: Stone Luster',
    'Evil Releasing Method',
    'Fire Release: Dragon Fire Technique',
    'Fire Release: Great Dragon Fire Technique',
    'Fire Release: Great Fireball Technique',
    'Fire Release: Phoenix Sage Fire Technique',
    'Genjutsu: Sharingan',
    'Hidden Shadow Snake Hands',
    'Human Path',
    'Hurricane Thunderclap — Majestic Attire Sword Stroke',
    "Indra's Arrow",
    'Kirin',
    'Lightning Flash',
    'Lion Combo',
    'Lorentz Gun (Novel only)',
    'Majestic Attire: Susanoo',
    'Manipulated Shuriken Technique',
    'Manipulating Windmill Triple Blades',
    'Moonlight',
    'Naka Shrine Pass Technique',
    'Naraka Path',
    'Orochimaru-Style Body Replacement Technique',
    'Outer Path',
    'Pachinko Technique (Anime only)',
    'Peregrine Falcon Drop',
    'Preta Path',
    'Reverse Summoning Technique',
    "Sasuke Uchiha's Space–Time Dōjutsu",
    'Scorch Release: Halo Hurricane Jet Black Arrow Style Zero',
    'Shadow Clone Technique',
    'Shadow Shuriken Technique',
    'Shadow of the Dancing Leaf',
    'Six Paths Technique',
    'Six Paths Yin Power',
    'Six Paths — Chibaku Tensei',
    'Strong Fist',
    'Summoning Technique (Hawk, Snake)',
    'Summoning: Lightning Flash Blade Creation',
    'Supercooled Water Technique',
    'Surging Fire Wild Dance',
    'Susanoo',
    'Susanoo: Captive Slash',
    'Susanoo: Chidori',
    'Susanoo: Crush',
    'Susanoo: Fist',
    'Susanoo: Great Fireball Technique (Anime only)',
    'Sword of Kagutsuchi',
    'Sword of Kusanagi: Chidori Katana',
    'Uchiha Style Shurikenjutsu: "Lightning": Triple',
    'Water Release: Water Formation Wall (Novel only)'],
   'natureType': ['Lightning Release  (Affinity; Anime only)',
    'Fire Release',
    'Wind Release',
    'Earth Release',
    'Water Release',
    'Yin Release'],
   'personal': {'birthdate': 'July 23',
    'sex': 'Male',
    'age': {'Part I': '12–13', 'Part II': '16–17', 'Academy Graduate': '12'},
    'height': {'Part I': '150.8cm - 153.2cm',
     'Part II': '168cm',
     'Blank Period': '182cm'},
    'weight': {'Part I': '42.2kg - 43.5kg', 'Part II': '52.2kg'},
    'bloodType': 'AB',
    'kekkeiGenkai': ['Sharingan', 'Eternal Mangekyō Sharingan', 'Rinnegan'],
    'classification': 'Missing-nin',
    'occupation': 'Head of the Uchiha Clan',
    'affiliation': ['Konohagakure', 'Otogakure', 'Ryūchi Cave', 'Akatsuki'],
    'team': ['Team Kakashi', 'Sound Four', 'Taka'],
    'clan': 'Uchiha',
    'titles': ['うちはサスケUchihaSasuke',
     'childOfTheProphecy(予言の子,YogenNoKo)',
     'sasukeOfTheSharingan(写輪眼のサスケ,SharinganNoSasuke)',
     'supportingKage(支う影,Sasaukage,LiterallyMeaning:SupportingShadow)']},
   'rank': {'ninjaRank': {'Part I': 'Genin'}, 'ninjaRegistration': '012606'},
   'tools': ['Bow & Arrow',
    'Fūma Shuriken',
    'Katar',
    'Kusari (Anime only)',
    'Mind Awakening Pill',
    'Scalpel (Anime only)',
    'Sword',
    'Sword of Kusanagi',
    'Wire Strings'],
   'voiceActors': {'japanese': ['Noriaki Sugiyama',
     'Nao Tōyama   (Infant and Child)'],
    'english': ['Yuri Lowenthal', 'Erica Mendez   (Infant)']}},
  {'id': 1299,
   'name': 'Madara Uchiha',
   'images': ['https://static.wikia.nocookie.net/naruto/images/f/fd/Madara.png'],
   'debut': {'manga': 'Naruto Chapter #370',
    'anime': 'Naruto Shippūden Episode #130',
    'novel': 'Kakashi Hiden: Lightning in the Icy Sky  (Mentioned)',
    'movie': 'The Last: Naruto the Movie',
    'game': 'Naruto Shippūden: Ultimate Ninja Storm 2',
    'ova': 'Naruto Shippūden: UNSG anime cutscenes',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Tajima Uchiha', 'brother': 'Izuna Uchiha'},
   'jutsu': ['Animal Path',
    'Asura Path',
    'Black Receiver',
    'Blocking Technique Absorption Seal',
    'Chibaku Tensei',
    'Demonic Statue Chains',
    'Deva Path',
    'Evil Disturbance Waltz',
    'Fire Release: Dragon Flame Release Song Technique',
    'Fire Release: Great Fire Annihilation',
    'Fire Release: Great Fire Destruction',
    'Fire Release: Great Fireball Technique',
    'Fire Release: Great Flame Flower (Anime only)',
    'Fire Release: Hiding in Ash and Dust Technique',
    'Forbidden Individual Curse Tag',
    'Genjutsu: Sharingan',
    'God: Nativity of a World of Trees',
    'Gunbai Fanned Wind (Anime only)',
    'Hiding in Surface Technique',
    'Human Path',
    'Infinite Tsukuyomi',
    'Izanagi',
    'Kamui',
    'Limbo: Border Jail',
    'Majestic Attire: Susanoo',
    'Multiple Wood Release Clone Technique',
    'Naraka Path',
    'Outer Path',
    'Preta Path',
    'Regeneration Ability',
    'Sage Art: Storm Release Light Fang',
    'Sage Art: Yin Release Lightning Dispatch',
    'Sensing Technique',
    'Shadow Clone Technique',
    'Six Paths Senjutsu',
    'Six Paths Technique',
    'Six Paths Ten-Tails Coffin Seal',
    'Summoning Technique (Demonic Statue of the Outer Path, Kurama)',
    'Summoning: Demonic Statue of the Outer Path',
    'Susanoo',
    'Susanoo: Fist',
    'Tengai Shinsei',
    'Transcription Seal: Izanagi',
    'Truth-Seeking Ball',
    'Uchiha Return',
    'Will Materialisation',
    'Wood Clone Technique',
    'Wood Release Secret Technique: Nativity of a World of Trees',
    'Wood Release: Advent of a World of Flowering Trees',
    'Wood Release: Wood Dragon Technique',
    'Yasaka Magatama'],
   'natureType': ['Fire Release',
    'Wind Release',
    'Lightning Release',
    'Earth Release',
    'Water Release',
    'Wood Release',
    'Storm Release',
    'Yin Release',
    'Yang Release',
    'Yin–Yang Release'],
   'personal': {'birthdate': 'December 24',
    'sex': 'Male',
    'status': 'Deceased',
    'height': {'Part II': '179cm'},
    'weight': {'Part II': '71.3kg'},
    'bloodType': 'O',
    'kekkeiGenkai': ['Sharingan',
     'Eternal Mangekyō Sharingan',
     'Rinnegan',
     'Wood Release',
     'Storm Release'],
    'kekkeiMōra': 'Rinne Sharingan',
    'classification': ['Jinchūriki', 'Missing-nin', 'Sensor Type', 'Sage'],
    'tailedBeast': 'Ten-Tails (Forms)',
    'occupation': ['Co-founder of Konohagakure',
     'Head of the Uchiha clan  (Former)'],
    'affiliation': ['Konohagakure', 'Akatsuki'],
    'partner': ['Obito Uchiha', 'Black Zetsu'],
    'clan': 'Uchiha',
    'titles': ['うちはマダラUchihaMadara',
     'secondSixPaths(二人目の六道,FutarimeNoRikudō)',
     'saviourOfThisWorld(この世の救世主,KonoYoNoKyūseishu)',
     'ghostOfTheUchiha(うちはの亡霊,UchihaNoBōrei)']},
   'tools': ['Fūma Shuriken',
    'Gunbai',
    'Kama',
    'Spear (Anime only)',
    'Sword',
    'Tantō (Anime only)'],
   'uniqueTraits': ['Can absorb chakra'],
   'voiceActors': {'japanese': ['Naoya Uchida', 'Gō Inoue   (Child)'],
    'english': ['Neil Kaplan', 'Xander Mobus   (Child)']}},
  {'id': 376,
   'name': 'Kakashi Hatake',
   'images': ['https://static.wikia.nocookie.net/naruto/images/2/27/Kakashi_Hatake.png',
    'https://static.wikia.nocookie.net/naruto/images/2/25/Kakashi_Part_III.png'],
   'debut': {'manga': 'Naruto Chapter #3',
    'anime': 'Naruto Episode #3',
    'novel': 'Naruto: Innocent Heart, Demonic Blood',
    'movie': 'Naruto the Movie: Ninja Clash in the Land of Snow',
    'game': 'Naruto: Konoha Ninpōchō',
    'ova': 'Find the Four-Leaf Red Clover!',
    'appearsIn': 'Anime, Manga, Novel, Game, Movie'},
   'family': {'father': 'Sakumo Hatake'},
   'jutsu': ['Area Scanning Technique',
    'Chidori',
    'Demonic Illusion: Hell Viewing Technique',
    'Earth Release: Double Suicide Decapitation Technique',
    'Earth Release: Earth Wave Technique (Anime only)',
    'Earth Release: Earth-Style Wall',
    'Earth Release: Hiding Like a Mole Technique',
    'Earth Release: Multiple Earth-Style Wall (Anime only)',
    'Earth Release: Rending Drill Fang',
    'Eight Gates',
    'Evil Sealing Method',
    'Eye Mind Reading (Anime only)',
    'Fire Release: Great Fireball Technique (Anime only)',
    'Fire Release: Water Mist (Novel only)',
    'Flying Revolving Sword (Anime only)',
    'Front Lotus (Anime only)',
    'Genjutsu: Sharingan',
    'Ground Splitting Technique',
    'Hiding in Mist Technique (Anime only)',
    'Ice Release: One Horned White Whale',
    'Kamui',
    'Kamui Lightning Cutter',
    'Kamui Shuriken',
    'Lightning Cutter',
    'Lightning Release: Lightning Beast Tracking Fang',
    'Lightning Release: Purple Electricity',
    'Lightning Release: Shadow Clone Technique',
    'Lightning Transmission',
    'Multiple Shadow Clone Technique',
    'One Thousand Years of Death',
    'Peregrine Falcon Drop (Anime only)',
    'Rasengan',
    'Shadow Clone Technique',
    'Shadow of the Dancing Leaf (Anime only)',
    'Silent Killing',
    'Strong Fist (Anime only)',
    'Summoning Technique (Ninken)',
    'Summoning: Earth Release: Tracking Fang Technique',
    'Susanoo',
    'Water Clone Technique',
    'Water Release: Great Waterfall Technique',
    'Water Release: Water Beast',
    'Water Release: Water Bullet Technique',
    'Water Release: Water Dragon Bullet Technique',
    'Water Release: Water Formation Wall',
    'Water Release: Water Shark Bullet Technique',
    'White Light Blade'],
   'natureType': ['Lightning Release  (Affinity)',
    'Earth Release',
    'Water Release',
    'Fire Release',
    'Wind Release',
    'Yin Release',
    'Yang Release'],
   'personal': {'birthdate': 'September 15',
    'sex': 'Male',
    'age': {'Part I': '26–27',
     'Part II': '29–31',
     'Academy Graduate': '5',
     'Chunin Promotion': '6'},
    'height': {'Part I': '181cm'},
    'weight': {'Part I': '67.5kg'},
    'bloodType': 'O',
    'kekkeiGenkai': ['Sharingan', 'Mangekyō Sharingan'],
    'occupation': ['Anbu Captain  (Former)',
     'Third Division Commander of the Allied Shinobi Forces',
     'Hokage',
     'Genin Exams Proctor  (Anime only)'],
    'affiliation': ['Konohagakure',
     'Root  (Anime only)',
     'Allied Shinobi Forces'],
    'team': ['Team Minato',
     'Team Ro  (Anime only)',
     'Team Kakashi',
     'Kazekage Rescue Team',
     'Team Asuma  (Temporarily)',
     'Team One  (Anime only)',
     'Team 8  (Temporarily)',
     'Eight Man Squad',
     'Third Division'],
    'clan': 'Hatake',
    'titles': ['はたけカカシHatakeKakashi',
     'copyNinjaKakashi(コピー忍者のカカシ,KopīNinjaNoKakashi)',
     'kakashiOfTheSharingan(写輪眼のカカシ,SharinganNoKakashi,LiterallyMeaning:KakashiOfTheCopyWheelEye)',
     'heroOfTheSharingan(写輪眼の英雄,SharinganNoEiyū,LiterallyMeaning:HeroOfTheCopyWheelEye)',
     'cold-bloodedKakashi(冷血カカシ,ReiketsuKakashi)',
     'friend-killerKakashi(仲間殺しのカカシ,NakamagoroshiNoKakashi)',
     'sixthHokage(六代目火影,RokudaimeHokage,LiterallyMeaning:SixthFireShadow)',
     'sukea(スケア)']},
   'rank': {'ninjaRank': {'Part I': 'Jōnin', 'Blank Period': 'Kage'},
    'ninjaRegistration': '009720'},
   'tools': ['Bow & Arrow (Anime only)',
    'Chakra-Suppressing Seal',
    'Flying Thunder God Kunai',
    'Kubikiribōchō',
    'Kusarigama (Anime only)',
    'Lightning Barrel (Anime only)',
    'Makibishi',
    'Sword',
    'Tantō',
    'White Light Chakra Sabre',
    'Wire Strings'],
   'voiceActors': {'japanese': ['Kazuhiko Inoue',
     'Mutsumi Tamura  (Child)',
     'Kenichi Suzumura   (Sukea)'],
    'english': ['Dave Wittenberg', 'Xander Mobus   (Sukea)']}},
  {'id': 928,
   'name': 'Orochimaru',
   'images': ['https://static.wikia.nocookie.net/naruto/images/1/14/Orochimaru_Infobox.png',
    'https://static.wikia.nocookie.net/naruto/images/b/be/Orochimaru_Part_III.png'],
   'debut': {'manga': 'Naruto Chapter #45',
    'anime': 'Naruto Episode #27',
    'novel': 'Sasuke Shinden: Book of Sunrise',
    'movie': 'Naruto Shippūden the Movie: Bonds',
    'game': 'Naruto: Ninja Council',
    'ova': 'Hidden Leaf Village Grand Sports Festival!',

In [ ]:
df = pd.json_normalize(json_data["characters"]) # Making a dataFrame based on Characters
df.head()

,id,name,images,jutsu,natureType,tools,debut.manga,debut.anime,debut.novel,debut.movie,...,family.host,personal.age.Blank Period,personal.age.Boruto Movie,personal.age.Boruto Manga,personal.height.Boruto Movie,personal.height.Boruto Manga,family.niece,family.lover,family.creator,family.genetic template
0,1344,Naruto Uzumaki,[https://static.wikia.nocookie.net/naruto/imag...,"[All Directions Shuriken, Baryon Mode, Big Bal...","[Wind Release (Affinity), Lightning Release, ...","[Absorbing Hand, Bō (Anime only), Chakra Blade...",Naruto Chapter #1,Naruto Episode #1,"Naruto: Innocent Heart, Demonic Blood",Naruto the Movie: Ninja Clash in the Land of Snow,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1307,Sasuke Uchiha,[https://static.wikia.nocookie.net/naruto/imag...,"[Afterglow, Amaterasu, Amaterasu: Flame Wrappi...","[Lightning Release (Affinity; Anime only), Fi...","[Bow & Arrow, Fūma Shuriken, Katar, Kusari (An...",Naruto Chapter #3,Naruto Episode #1,"Naruto: Innocent Heart, Demonic Blood",Naruto the Movie: Ninja Clash in the Land of Snow,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1299,Madara Uchiha,[https://static.wikia.nocookie.net/naruto/imag...,"[Animal Path, Asura Path, Black Receiver, Bloc...","[Fire Release, Wind Release, Lightning Release...","[Fūma Shuriken, Gunbai, Kama, Spear (Anime onl...",Naruto Chapter #370,Naruto Shippūden Episode #130,Kakashi Hiden: Lightning in the Icy Sky (Ment...,The Last: Naruto the Movie,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,376,Kakashi Hatake,[https://static.wikia.nocookie.net/naruto/imag...,"[Area Scanning Technique, Chidori, Demonic Ill...","[Lightning Release (Affinity), Earth Release,...","[Bow & Arrow (Anime only), Chakra-Suppressing ...",Naruto Chapter #3,Naruto Episode #3,"Naruto: Innocent Heart, Demonic Blood",Naruto the Movie: Ninja Clash in the Land of Snow,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,928,Orochimaru,[https://static.wikia.nocookie.net/naruto/imag...,"[Binding Snake Glare Spell, Casualty Puppet (A...","[Wind Release, Lightning Release, Earth Releas...","[Genjutsu Pill (Anime only), Mind Awakening Pi...",Naruto Chapter #45,Naruto Episode #27,Sasuke Shinden: Book of Sunrise,Naruto Shippūden the Movie: Bonds,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = df[["name", "jutsu", "natureType", "tools"]] # Displaying selected columns
df.head()

,name,jutsu,natureType,tools
0,Naruto Uzumaki,"[All Directions Shuriken, Baryon Mode, Big Bal...","[Wind Release (Affinity), Lightning Release, ...","[Absorbing Hand, Bō (Anime only), Chakra Blade..."
1,Sasuke Uchiha,"[Afterglow, Amaterasu, Amaterasu: Flame Wrappi...","[Lightning Release (Affinity; Anime only), Fi...","[Bow & Arrow, Fūma Shuriken, Katar, Kusari (An..."
2,Madara Uchiha,"[Animal Path, Asura Path, Black Receiver, Bloc...","[Fire Release, Wind Release, Lightning Release...","[Fūma Shuriken, Gunbai, Kama, Spear (Anime onl..."
3,Kakashi Hatake,"[Area Scanning Technique, Chidori, Demonic Ill...","[Lightning Release (Affinity), Earth Release,...","[Bow & Arrow (Anime only), Chakra-Suppressing ..."
4,Orochimaru,"[Binding Snake Glare Spell, Casualty Puppet (A...","[Wind Release, Lightning Release, Earth Releas...","[Genjutsu Pill (Anime only), Mind Awakening Pi..."